name: Deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no dockerserver@192.168.0.103 << 'EOF'
            set -e
            cd /var/www/nuy-laundry
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF